[package]
name = "tree-sitter-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cc = "*"
tree-sitter = "0.20.10"

[build-dependencies]
cc="*"
